syntax = "proto3";

package assetmodel;

service AssetModelService {

    rpc GetAssetHierarchy(GetAssetHierarchyRequest)
        returns (GetAssetHierarchyResponse);
}

message GetAssetHierarchyRequest {

}

message GetAssetHierarchyResponse {
    repeated AssetNode roots = 1;
}


message AssetNode {
  string id = 1;
  string name = 2;
  string asset_type_id = 3;
  repeated AssetVariable variables = 4;
  repeated AssetNode children = 5;
}

message AssetVariable {
  string id = 1;
  string name = 2;
  string data_type = 3;
  string unit = 4;
}
